/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerManagementWorkArea;

//import userinterface.CustomerServiceWorkArea.*;
import Business.Dao.Customer;
import Business.Dao.CustomerDirectory;
import Business.Dao.Order;
import Business.Dao.Product;
import Business.Dao.ProductDirectory;
import Business.EcoSystem;
import Business.Organization.CustomerServiceOrganization;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CMOrderCheckWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class CheckJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Customer customer;
    private CMOrderCheckWorkRequest request;
    private ProductDirectory productDirectory;
    
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public CheckJPanel(JPanel userProcessContainer, Customer customer,CMOrderCheckWorkRequest request) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.customer = customer;
        this.request = request;
        viewInfo(customer,request);
        
    }
    
    public void viewInfo(Customer customer,CMOrderCheckWorkRequest request){
        addrTxt.setText(customer.getCusAddress());
        balTxt.setText(String.valueOf(customer.getCusBalance()));
        Order o = request.getOrder();
        double price = o.getPrice();
        priceText.setText(String.valueOf(price*o.getNum()));
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        checkBtn = new javax.swing.JButton();
        address = new javax.swing.JLabel();
        address1 = new javax.swing.JLabel();
        balTxt = new javax.swing.JTextField();
        addrTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        denyBtn = new javax.swing.JButton();
        address2 = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 237, 237));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 204));
        jLabel1.setText("Check Information");

        checkBtn.setForeground(new java.awt.Color(255, 102, 204));
        checkBtn.setText("Approve");
        checkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBtnActionPerformed(evt);
            }
        });

        address.setForeground(new java.awt.Color(255, 102, 204));
        address.setText("customer Balance");

        address1.setForeground(new java.awt.Color(255, 102, 204));
        address1.setText("customer Address");

        balTxt.setForeground(new java.awt.Color(255, 102, 204));

        addrTxt.setForeground(new java.awt.Color(255, 102, 204));

        backBtn.setForeground(new java.awt.Color(255, 102, 204));
        backBtn.setText("< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        denyBtn.setForeground(new java.awt.Color(255, 102, 204));
        denyBtn.setText("Deny");
        denyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyBtnActionPerformed(evt);
            }
        });

        address2.setForeground(new java.awt.Color(255, 102, 204));
        address2.setText("Order Price");

        priceText.setForeground(new java.awt.Color(255, 102, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(address1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(balTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(checkBtn)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(denyBtn)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(address2)
                                                .addGap(28, 28, 28)
                                                .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(83, 83, 83))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel1)
                                .addGap(193, 193, 193))))
                    .addComponent(backBtn)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(backBtn)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address1)
                    .addComponent(addrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address)
                    .addComponent(balTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address2)
                    .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(denyBtn)
                    .addComponent(checkBtn))
                .addGap(103, 103, 103))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBtnActionPerformed
        // TODO add your handling code here:
        request.getOrder().setStatus(1);
        request.setStatus("0-Completed");
        
        
    }//GEN-LAST:event_checkBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void denyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyBtnActionPerformed
        // TODO add your handling code here:
        request.getOrder().setStatus(12);
        request.setStatus("0-Completed");
    }//GEN-LAST:event_denyBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrTxt;
    private javax.swing.JLabel address;
    private javax.swing.JLabel address1;
    private javax.swing.JLabel address2;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField balTxt;
    private javax.swing.JButton checkBtn;
    private javax.swing.JButton denyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField priceText;
    // End of variables declaration//GEN-END:variables
}
