/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Airliner;

import Travel_Agency.Flight;
import Travel_Agency.Flights;
import Travel_Agency.Airliner;
import Travel_Agency.AirlinerList;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhaowenxiao
 */
public class AirlinerMngPanel extends javax.swing.JPanel {

    /**
     * Creates new form AirlinerPanel
     */
    JPanel processPanel;
    AirlinerList airliners;
    ArrayList<Airliner> airlinerList;
    
    

    public AirlinerMngPanel(JPanel processPanel, AirlinerList airliners) {
        initComponents();
        this.airliners=airliners;
        this.processPanel=processPanel;
        this.airlinerList= airliners.getAirliners();
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAirliners = new javax.swing.JTable();
        btnNewAirliner = new javax.swing.JButton();
        btnViewAirliner = new javax.swing.JButton();
        btnFleet = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(153, 153, 255));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 255));
        jLabel1.setText("Manage Airliners");

        tableAirliners.setBackground(new java.awt.Color(153, 102, 255));
        tableAirliners.setForeground(new java.awt.Color(255, 255, 255));
        tableAirliners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Name", "Address", "Total Airplanes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAirliners);
        if (tableAirliners.getColumnModel().getColumnCount() > 0) {
            tableAirliners.getColumnModel().getColumn(0).setResizable(false);
            tableAirliners.getColumnModel().getColumn(1).setResizable(false);
            tableAirliners.getColumnModel().getColumn(2).setResizable(false);
        }

        btnNewAirliner.setBackground(new java.awt.Color(204, 204, 204));
        btnNewAirliner.setForeground(new java.awt.Color(153, 102, 255));
        btnNewAirliner.setText("New Airliner");
        btnNewAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAirlinerActionPerformed(evt);
            }
        });

        btnViewAirliner.setBackground(new java.awt.Color(204, 204, 204));
        btnViewAirliner.setForeground(new java.awt.Color(153, 102, 255));
        btnViewAirliner.setText("View Airliner");
        btnViewAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAirlinerActionPerformed(evt);
            }
        });

        btnFleet.setBackground(new java.awt.Color(204, 204, 204));
        btnFleet.setForeground(new java.awt.Color(153, 102, 255));
        btnFleet.setText("Add fleet for airliner");
        btnFleet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFleetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnFleet)
                        .addGap(18, 18, 18)
                        .addComponent(btnNewAirliner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewAirliner))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel1)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAirliner)
                    .addComponent(btnNewAirliner)
                    .addComponent(btnFleet))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populate() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel dtm = (DefaultTableModel)tableAirliners.getModel();
        dtm.setRowCount(0);
        
        for(Airliner a:airlinerList){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=a;
            row[1]=a.getAddr();
            row[2]=a.getTotalairplane();
            //row[3]=a.getDescription();
            dtm.addRow(row);
        }
    
    
    
    }
    
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        processPanel.remove(this);
        CardLayout layout = (CardLayout)(processPanel).getLayout();
        layout.first(processPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNewAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAirlinerActionPerformed
        // TODO add your handling code here:
        NewAirlinerPanel newAirpanel = new NewAirlinerPanel(processPanel, airliners); 
        processPanel.add("NewArilinersPanel", newAirpanel);
        CardLayout layout = (CardLayout) processPanel.getLayout();
        layout.next(processPanel);
    }//GEN-LAST:event_btnNewAirlinerActionPerformed

    private void btnViewAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAirlinerActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableAirliners.getSelectedRow();
        if(selectedRow>=0){
            //add a jpanel
            Airliner airliner = (Airliner) tableAirliners.getValueAt(selectedRow,0);
            ViewAirlinerPanel viewAirpanel = new ViewAirlinerPanel(processPanel, airliner); 
            processPanel.add("viewArilinersPanel", viewAirpanel);
            CardLayout layout = (CardLayout) processPanel.getLayout();
            layout.next(processPanel);
        }
        
        else
          JOptionPane.showMessageDialog(null, "Please select a row", "warning",JOptionPane.WARNING_MESSAGE);  
        
        
    }//GEN-LAST:event_btnViewAirlinerActionPerformed

    private void btnFleetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFleetActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableAirliners.getSelectedRow();
        if(selectedRow>=0){
            
            Airliner airliner = (Airliner) tableAirliners.getValueAt(selectedRow,0);
            AddFleetPanel fleet = new AddFleetPanel(processPanel, airliner); 
            processPanel.add("FleetPanel", fleet);
            CardLayout layout = (CardLayout) processPanel.getLayout();
            layout.next(processPanel);
        }
        
        else
           JOptionPane.showMessageDialog(null, "Please select a row", "warning",JOptionPane.WARNING_MESSAGE);   
    }//GEN-LAST:event_btnFleetActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFleet;
    private javax.swing.JButton btnNewAirliner;
    private javax.swing.JButton btnViewAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAirliners;
    // End of variables declaration//GEN-END:variables

    
}
