/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Ticket;
import Business.Tickets;
import Travel_Agency.Flight;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zlt1997
 */
public class BookTicketPanel extends javax.swing.JPanel {
        private JPanel rightPanel;
        private Flight flight;
        private Tickets customerCatalog;
    /**
     * Creates new form BookTicketPanel
     */
    public BookTicketPanel(JPanel rightPanel, Flight flight,Tickets customerCatalog) {
        initComponents();
        SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
        this.rightPanel=rightPanel;
        this.flight=flight;
        this.customerCatalog=customerCatalog;
        txtFlightno.setText(flight.getFlightID());
        txtTo.setText(flight.getToAirport());
        txtfrom.setText(flight.getFromAirport());
        txtdate.setText(sdf.format(flight.getArriveDate()));
        
        
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        lblFlightNo = new javax.swing.JLabel();
        txtFlightno = new javax.swing.JTextField();
        lblFlightNo1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblTo = new javax.swing.JLabel();
        txtfrom = new javax.swing.JTextField();
        txtTo = new javax.swing.JTextField();
        lblfrom = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        Comfirm = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Ticket");

        lblDate.setForeground(new java.awt.Color(102, 51, 255));
        lblDate.setText("Date:");

        txtdate.setForeground(new java.awt.Color(102, 51, 255));
        txtdate.setEnabled(false);

        lblFlightNo.setForeground(new java.awt.Color(102, 51, 255));
        lblFlightNo.setText("FlightNo:");

        txtFlightno.setForeground(new java.awt.Color(102, 51, 255));
        txtFlightno.setEnabled(false);

        lblFlightNo1.setForeground(new java.awt.Color(102, 51, 255));
        lblFlightNo1.setText("Customer Name: ");

        txtname.setForeground(new java.awt.Color(102, 51, 255));

        lblTo.setForeground(new java.awt.Color(102, 51, 255));
        lblTo.setText("To:");

        txtfrom.setForeground(new java.awt.Color(102, 51, 255));
        txtfrom.setEnabled(false);

        txtTo.setForeground(new java.awt.Color(102, 51, 255));
        txtTo.setEnabled(false);

        lblfrom.setForeground(new java.awt.Color(102, 51, 255));
        lblfrom.setText("From:");

        btnBack.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 102, 255));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        Comfirm.setForeground(new java.awt.Color(102, 51, 255));
        Comfirm.setText("comfirm");
        Comfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblTo)
                                        .addGap(65, 65, 65))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblfrom)
                                        .addGap(49, 49, 49)))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtfrom)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFlightNo1)
                                    .addComponent(lblDate)
                                    .addComponent(lblFlightNo))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFlightno)
                                    .addComponent(txtname)
                                    .addComponent(txtdate))))))
                .addGap(227, 227, 227))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Comfirm)
                .addGap(349, 349, 349))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(3, 3, 3)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlightNo)
                    .addComponent(txtFlightno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlightNo1)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfrom)
                    .addComponent(txtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTo)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(Comfirm)
                .addContainerGap(208, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComfirmActionPerformed
      Ticket t=new Ticket();
        if (txtname.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Name can't be empty");
            return;
        }else t.setCustomerID(txtname.getText());
      
      t.setFlightID(txtFlightno.getText());
      customerCatalog.addticket(t);
        JOptionPane.showMessageDialog(this, "Successful");
        // TODO add your handling code here:
    }//GEN-LAST:event_ComfirmActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
            rightPanel.remove(this);
            CardLayout layout= (CardLayout) rightPanel.getLayout();
            layout.previous(rightPanel);        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comfirm;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFlightNo;
    private javax.swing.JLabel lblFlightNo1;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lblfrom;
    private javax.swing.JTextField txtFlightno;
    private javax.swing.JTextField txtTo;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtfrom;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
