/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Travel_Agency.Airliner;
import Travel_Agency.Flight;
import Travel_Agency.Flights;
import Travel_Agency.AirlinerList;
import Travel_Agency.Airplane;
import Utils.ArrayListComboBoxModel;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author llm
 */
public class CreateFlightJPanel extends javax.swing.JPanel {
     private JPanel rightPanel;
     private Flights flights;
     private AirlinerList airliners;
    /**
     * Creates new form CreateCustomerJPanel
     */
    public CreateFlightJPanel(JPanel rightPanel,AirlinerList airlines,Flights flights) {
        initComponents();
        this.rightPanel=rightPanel;
        this.flights=flights;
        this.airliners=airlines;
        create1();
        Airlinercombo.setSelectedIndex(0);
        create2();
        airplanecombo.setSelectedIndex(0);
        
    }
    
   private void create1()
   {
      ArrayList<String> locationLists1 = new ArrayList();
       for (Airliner a : airliners.getAirliners()) {
           locationLists1.add(a.getAirlinerNames());
       }
      ArrayListComboBoxModel model = new ArrayListComboBoxModel(locationLists1);
      Airlinercombo.setModel(model);
   }
   
   private void create2()
   {
      ArrayList<String> locationLists1 = new ArrayList();
       for (Airplane a : airliners.SearchAirliners(Airlinercombo.getSelectedItem().toString()).getAirList()) {
           locationLists1.add(a.getSerialNum());
       }
      ArrayListComboBoxModel model = new ArrayListComboBoxModel(locationLists1);
      airplanecombo.setModel(model);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        txtyear = new javax.swing.JTextField();
        lblAirl = new javax.swing.JLabel();
        lblFlightNo = new javax.swing.JLabel();
        txtFlightno = new javax.swing.JTextField();
        lbltime = new javax.swing.JLabel();
        lblfrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        txtfrom = new javax.swing.JTextField();
        txtTo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Airlinercombo = new javax.swing.JComboBox<>();
        airplanecombo = new javax.swing.JComboBox<>();
        TimeCombox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        title.setForeground(new java.awt.Color(102, 51, 255));
        title.setText("Create Flight");

        createBtn.setForeground(new java.awt.Color(102, 51, 255));
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 102, 255));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblDate.setForeground(new java.awt.Color(102, 51, 255));
        lblDate.setText("Date:");

        txtyear.setForeground(new java.awt.Color(102, 51, 255));

        lblAirl.setForeground(new java.awt.Color(102, 51, 255));
        lblAirl.setText("Airliner:");

        lblFlightNo.setForeground(new java.awt.Color(102, 51, 255));
        lblFlightNo.setText("FlightNo:");

        txtFlightno.setForeground(new java.awt.Color(102, 51, 255));
        txtFlightno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFlightnoActionPerformed(evt);
            }
        });

        lbltime.setForeground(new java.awt.Color(102, 51, 255));
        lbltime.setText("Time:");

        lblfrom.setForeground(new java.awt.Color(102, 51, 255));
        lblfrom.setText("From:");

        lblTo.setForeground(new java.awt.Color(102, 51, 255));
        lblTo.setText("To:");

        txtfrom.setForeground(new java.awt.Color(102, 51, 255));

        txtTo.setForeground(new java.awt.Color(102, 51, 255));

        jLabel1.setForeground(new java.awt.Color(102, 51, 255));
        jLabel1.setText("Airplane:");

        Airlinercombo.setForeground(new java.awt.Color(102, 51, 255));
        Airlinercombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirlinercomboActionPerformed(evt);
            }
        });

        airplanecombo.setForeground(new java.awt.Color(102, 51, 255));
        airplanecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        TimeCombox.setForeground(new java.awt.Color(102, 51, 255));
        TimeCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Day", "Evening" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(232, 232, 232)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbltime)
                                            .addComponent(lblAirl)
                                            .addComponent(lblDate)
                                            .addComponent(jLabel1))
                                        .addGap(35, 35, 35))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTo)
                                        .addGap(65, 65, 65)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblfrom)
                                    .addGap(49, 49, 49)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFlightNo)
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFlightno)
                            .addComponent(txtfrom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(createBtn))
                            .addComponent(Airlinercombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtyear)
                            .addComponent(TimeCombox, 0, 150, Short.MAX_VALUE)
                            .addComponent(airplanecombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnBack)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title)
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlightNo)
                    .addComponent(txtFlightno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfrom)
                    .addComponent(txtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTo)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirl)
                    .addComponent(Airlinercombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltime)
                    .addComponent(TimeCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(airplanecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(createBtn)
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFlightnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFlightnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFlightnoActionPerformed

  
        
   
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
           this.rightPanel.remove(this);
           CardLayout layout=(CardLayout)this.rightPanel.getLayout();
           
           Component[] comps=this.rightPanel.getComponents();
           for(Component comp:comps)
           {
               if (comp instanceof TravelAgencyPanel) {
                   TravelAgencyPanel manageP=(TravelAgencyPanel) comp;
                   manageP.populate();
               }
           }
           layout.previous(rightPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
           Flight f=new Flight();
           DateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");  
           
           if (txtFlightno.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "FlightNO Can't be null");
            return;
        }else f.setFlightID(txtFlightno.getText());
           
           if (txtfrom.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "From City Can't be null");
            return;
        }else f.setFromAirport(txtfrom.getText());
           
           if (txtTo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "To City Can't be null");
            return;
        }else f.setToAirport(txtTo.getText());
           
           
           f.setTime(TimeCombox.getSelectedItem().toString());
           f.setAirliner(Airlinercombo.getSelectedItem().toString());
           try {
            f.setArriveDate(format1.parse(txtyear.getText()));
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Date format is not right");
            return;
        }
           
           f.setAirplane(airplanecombo.getSelectedItem().toString());
       
           flights.addflight(f);
           JOptionPane.showMessageDialog(this, "Success");
        // TODO add your handling code here:
    }//GEN-LAST:event_createBtnActionPerformed

    private void AirlinercomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirlinercomboActionPerformed
                create2();
                airplanecombo.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_AirlinercomboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Airlinercombo;
    private javax.swing.JComboBox<String> TimeCombox;
    private javax.swing.JComboBox<String> airplanecombo;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAirl;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFlightNo;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lblfrom;
    private javax.swing.JLabel lbltime;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtFlightno;
    private javax.swing.JTextField txtTo;
    private javax.swing.JTextField txtfrom;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
