/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Ticket;
import Business.Tickets;
import Interface.Airliner.AirlinerMngPanel;
import Interface.customer.ManageMasterFlightScheduleJPanel;
import Interface.customer.ReserveSeats;
import Travel_Agency.Airliner;
import Travel_Agency.AirlinerList;
import Travel_Agency.Flights;
import Travel_Agency.initclass;
import java.awt.CardLayout;

/**
 *
 * @author llm
 */
public class MainJFrame extends javax.swing.JFrame {
     private AirlinerList airlinerList;
     private Flights flightlist;
     private Tickets tickets;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.airlinerList=new AirlinerList();
        this.flightlist=new Flights();
        this.tickets=new Tickets();
        initclass c= new initclass(flightlist, airlinerList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnTravelAgency = new javax.swing.JButton();
        btnReserveSeat = new javax.swing.JButton();
        btnBestFlightPlan = new javax.swing.JButton();
        btnAirliners = new javax.swing.JButton();
        processPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnTravelAgency.setForeground(new java.awt.Color(102, 51, 255));
        btnTravelAgency.setText("Travel Agency");
        btnTravelAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelAgencyActionPerformed(evt);
            }
        });

        btnReserveSeat.setForeground(new java.awt.Color(102, 51, 255));
        btnReserveSeat.setText("Reserve Seat");
        btnReserveSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveSeatActionPerformed(evt);
            }
        });

        btnBestFlightPlan.setForeground(new java.awt.Color(102, 51, 255));
        btnBestFlightPlan.setText("Best Flight Plan");
        btnBestFlightPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBestFlightPlanActionPerformed(evt);
            }
        });

        btnAirliners.setForeground(new java.awt.Color(102, 51, 255));
        btnAirliners.setText("Airliners");
        btnAirliners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlinersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAirliners, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnBestFlightPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReserveSeat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTravelAgency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(16, 16, 16))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btnTravelAgency)
                .addGap(47, 47, 47)
                .addComponent(btnReserveSeat)
                .addGap(43, 43, 43)
                .addComponent(btnBestFlightPlan)
                .addGap(40, 40, 40)
                .addComponent(btnAirliners)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(controlPanel);

        processPanel.setBackground(new java.awt.Color(255, 255, 255));
        processPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Travel Agency!");
        processPanel.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(processPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTravelAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelAgencyActionPerformed
      TravelAgencyPanel panel=new TravelAgencyPanel(processPanel,flightlist,airlinerList,tickets);
        processPanel.add("AccountMngwWorkAreaJPanel",panel);
        CardLayout layout= (CardLayout) processPanel.getLayout();
        layout.show(processPanel, "AccountMngwWorkAreaJPanel");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTravelAgencyActionPerformed

    private void btnReserveSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveSeatActionPerformed
        ReserveSeats panel = new ReserveSeats(processPanel,tickets,flightlist);
        processPanel.add("ReserveSeats",panel);
        CardLayout layout = (CardLayout)processPanel.getLayout();
        layout.show(processPanel,"ReserveSeats");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReserveSeatActionPerformed

    private void btnBestFlightPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBestFlightPlanActionPerformed
        ManageMasterFlightScheduleJPanel panel = new ManageMasterFlightScheduleJPanel(processPanel,flightlist);
        processPanel.add("ManageMasterFlightScheduleJPanel",panel);
        CardLayout layout = (CardLayout)processPanel.getLayout();
        layout.show(processPanel,"ManageMasterFlightScheduleJPanel");        // TODO add your handling code here:
    }//GEN-LAST:event_btnBestFlightPlanActionPerformed

    private void btnAirlinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlinersActionPerformed
         AirlinerMngPanel panel = new AirlinerMngPanel(processPanel,airlinerList);
        processPanel.add("AirlinerMngPanel",panel);
        CardLayout layout = (CardLayout)processPanel.getLayout();
        layout.show(processPanel,"AirlinerMngPanel");   
// TODO add your handling code here:
    }//GEN-LAST:event_btnAirlinersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAirliners;
    private javax.swing.JButton btnBestFlightPlan;
    private javax.swing.JButton btnReserveSeat;
    private javax.swing.JButton btnTravelAgency;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel processPanel;
    // End of variables declaration//GEN-END:variables
}
