/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupplierWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.WarehouseOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zhaowenxiao
 */
public class ApproveRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApproveRequestPanel
     */
    JPanel userProcessContainer;
    WorkRequest req;
    EcoSystem system;
    ArrayList<Network> networkList;
    UserAccount account;
    //Organization org;
    //Enterprise enterprise;
    
    public ApproveRequestPanel(JPanel userProcessContainer, WorkRequest req,EcoSystem system,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.req = req;
        this.system = system;
        this.networkList = system.getNetworkList();
        this.account = account;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        checkBoxAgree = new javax.swing.JCheckBox();
        btnApprove = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 237, 237));

        btnBack.setForeground(new java.awt.Color(255, 102, 204));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 204));
        jLabel1.setText("Approve Request");

        jScrollPane1.setForeground(new java.awt.Color(255, 102, 204));

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 102, 204));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("I. Definition of Force Majeure\n\n\"Force Majeure\" means all events that occurred after the signing of this Agreement and were not foreseeable at the time of signing this Agreement, whose occurrences and consequences cannot be avoided or overcome, and prevent any party from fulfilling its performance in whole or in part. Such events include earthquakes, typhoons, floods, fires, wars, disruptions in international or domestic transportation, epidemics, strikes, and other events deemed to be force majeure under Chinese law or general international business practice. A lack of funds on one side was a force majeure event.\n\nConsequences of Force Majeure\n\n1. If a force majeure event occurs that affects one party's performance of its obligations under this agreement, it will be suspended during the period of delay caused by force majeure and is not considered a breach of contract.\n\n\n\n3. In the event of a force majeure event, the parties shall immediately negotiate with each other to find a fair solution, and shall make every reasonable effort to minimize the impact of force majeure. If the occurrence or consequence of force majeure has caused significant obstacles to the operation of the joint venture company for more than six (6) months and the parties have not found a fair solution, then either party may begin the process of terminating this agreement in accordance with the provisions of Article 16. Provided that the party has fulfilled its obligations under this article.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        checkBoxAgree.setForeground(new java.awt.Color(255, 102, 204));
        checkBoxAgree.setText("I have read and agree to the above statement and am sure to approve the request from the company xx with the selected supplier");
        checkBoxAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAgreeActionPerformed(evt);
            }
        });

        btnApprove.setForeground(new java.awt.Color(255, 102, 204));
        btnApprove.setText("Approve");
        btnApprove.setActionCommand("");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(checkBoxAgree, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(btnApprove)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(checkBoxAgree)
                .addGap(32, 32, 32)
                .addComponent(btnApprove)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAgreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxAgreeActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        if(checkBoxAgree.isSelected()){
            req.setStatus("Request approved");
            req.setEnterSender("Supplier Agency");
            System.out.println(req.getEnterSender());
            Enterprise enterprise = getSalesEnterprise();
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if (organization instanceof WarehouseOrganization && organization.getOrganizationID() != 3){
                        for(WorkRequest request:organization.getWorkQueue().getWorkRequestList()){
                            if(request.getRequestDate().equals(req.getRequestDate())){
                                request.setStatus("Request approved");
                                request.setEnterSender("Supplier Agency");
                                JOptionPane.showMessageDialog(null, "Request approved!");
                                break;
                            }
                        }    
                    }    
            }
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        Component[] comps=this.userProcessContainer.getComponents();
        for(Component comp:comps)
        {
            if (comp instanceof SupplierWorkAreaJPanel) {
                SupplierWorkAreaJPanel manageP=(SupplierWorkAreaJPanel) comp;
                manageP.populateTableRequest();
               
            }
        }
        layout.show(userProcessContainer,"workArea");
        
    }//GEN-LAST:event_btnBackActionPerformed

    private final Network getNetwork(){
       
        for(Network network: networkList){
            if(network.getName().equals("1")){
                System.out.println("看看network: "+network);
                return network;
            }
        }
        return null;
    }
    
    private final Enterprise getSalesEnterprise(){
        Network net = getNetwork();
        
        for(Enterprise enterprise:net.getEnterpriseDirectory().getEnterpriseList()){
            System.out.println("Let me see the enterprise Name: "+enterprise.getName());
            if(enterprise.getName().equals("XX"))
                return enterprise;
        } 
        
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JCheckBox checkBoxAgree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
