/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupplierWorkArea;

import userinterface.WarehouseWorkArea.*;
import Business.Dao.Order;
import Business.Dao.OrderDirectory;
import Business.Dao.Product;
import Business.Dao.ProductDirectory;
import Business.Dao.Supplier;
import Business.Dao.SupplierDirectory;
import Business.Dao.SupplierProducts;
import userinterface.CustomerServiceWorkArea.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ContractorProductOrganization;
import Business.Organization.CustomerManagerOrganization;
import Business.Organization.CustomerServiceOrganization;
import Business.Organization.Organization;
import Business.Organization.SalesPersonOrganization;
import Business.Organization.WarehouseOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CMOrderCheckWorkRequest;
import Business.WorkQueue.SignSupplierRequest;
//import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ContractorProductOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private ProductDirectory  productDirectory;
    private SupplierDirectory  supplierDirectory;
    private Product product;
    private EcoSystem system;
    ArrayList<Network> networkList;
    /**
     * Creates new form SalesPersonWorkAreaJPanel
     */
    public SupplierWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, 
            ContractorProductOrganization organization, Enterprise enterprise,EcoSystem system
        ) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        this.supplierDirectory = organization.getSupplierDierectory();
        this.networkList = system.getNetworkList();

        valueLabel.setText(enterprise.getName());
        populateTableSupplier();
        populateComboSupplier();
        populateTableRequest();
        giveSupplier();
        System.out.println(this.organization.getWorkQueue().getWorkRequestList().isEmpty());
        
    }
    
    /*
    *Refresh supplier Combobox
    *
    */
   public void populateComboSupplier(){
 
        comboSupplierID.removeAllItems();
        comboSupplierName.removeAllItems();
        comboSupplierID.addItem("0");
        comboSupplierName.addItem("Select supplier name");
        for (Supplier s : supplierDirectory.getSupplierList()) {
            comboSupplierID.addItem(String.valueOf(s.getSupplierID()));
            comboSupplierName.addItem(s.getSupplierName());
        }
    }
   
   /*
    *Refresh product Combobox
    *
    */
   

    
 
    /*
    *Refresh supplier Table
    *
    */
    public void populateTableSupplier(){
        DefaultTableModel model = (DefaultTableModel) tableSuppliers.getModel();
        
        model.setRowCount(0);
        for (Supplier supplier : supplierDirectory.getSupplierList()){
            Object[] row = new Object[2];
            row[0] = supplier;
            row[1] = supplier.getSupplierName();

            model.addRow(row);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jtabWork = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableRequest = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnDecline = new javax.swing.JButton();
        btnViewRequest = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        comboSupplierID = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        comboSupplierName = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSuppliers = new javax.swing.JTable();
        btnViewSupplier = new javax.swing.JButton();
        btnDeleteSupplier = new javax.swing.JButton();
        btnAddSupplier = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        refreshTestJButton.setForeground(new java.awt.Color(255, 102, 204));
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 102, 204));
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setForeground(new java.awt.Color(255, 102, 204));
        valueLabel.setText("Supplier Agency");

        jtabWork.setForeground(new java.awt.Color(255, 102, 204));

        jPanel6.setBackground(new java.awt.Color(255, 237, 237));

        tableRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestDate", "Sender", "Message", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableRequest);
        if (tableRequest.getColumnModel().getColumnCount() > 0) {
            tableRequest.getColumnModel().getColumn(0).setResizable(false);
            tableRequest.getColumnModel().getColumn(1).setResizable(false);
            tableRequest.getColumnModel().getColumn(2).setResizable(false);
            tableRequest.getColumnModel().getColumn(3).setResizable(false);
        }

        btnApprove.setForeground(new java.awt.Color(255, 102, 204));
        btnApprove.setText("Approve Request");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnDecline.setForeground(new java.awt.Color(255, 102, 204));
        btnDecline.setText("Decline Request");
        btnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineActionPerformed(evt);
            }
        });

        btnViewRequest.setForeground(new java.awt.Color(255, 102, 204));
        btnViewRequest.setText("View Request Details");
        btnViewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApprove)
                    .addComponent(btnViewRequest)
                    .addComponent(btnDecline))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnViewRequest)
                        .addGap(18, 18, 18)
                        .addComponent(btnApprove)
                        .addGap(18, 18, 18)
                        .addComponent(btnDecline))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jtabWork.addTab("Contract requests", jPanel6);

        jPanel4.setBackground(new java.awt.Color(255, 237, 237));
        jPanel4.setForeground(new java.awt.Color(255, 102, 204));

        jLabel15.setForeground(new java.awt.Color(255, 102, 204));
        jLabel15.setText("Supplier ID");

        comboSupplierID.setForeground(new java.awt.Color(255, 102, 204));
        comboSupplierID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Supplier ID", "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setForeground(new java.awt.Color(255, 102, 204));
        jLabel16.setText("Supplier Name");

        comboSupplierName.setForeground(new java.awt.Color(255, 102, 204));
        comboSupplierName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Supplier Name", "Item 1", "Item 2", "Item 3", "Item 4" }));

        tableSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableSuppliers);
        if (tableSuppliers.getColumnModel().getColumnCount() > 0) {
            tableSuppliers.getColumnModel().getColumn(0).setResizable(false);
            tableSuppliers.getColumnModel().getColumn(1).setResizable(false);
        }

        btnViewSupplier.setForeground(new java.awt.Color(255, 102, 204));
        btnViewSupplier.setText("View Details");
        btnViewSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSupplierActionPerformed(evt);
            }
        });

        btnDeleteSupplier.setForeground(new java.awt.Color(255, 102, 204));
        btnDeleteSupplier.setText("Contract termination");
        btnDeleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSupplierActionPerformed(evt);
            }
        });

        btnAddSupplier.setForeground(new java.awt.Color(255, 102, 204));
        btnAddSupplier.setText("Sign new supplier");
        btnAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierActionPerformed(evt);
            }
        });

        btnSearch.setForeground(new java.awt.Color(255, 102, 204));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(comboSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(btnSearch))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewSupplier)
                            .addComponent(btnDeleteSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(comboSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(comboSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnViewSupplier)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteSupplier)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddSupplier)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jtabWork.addTab("View Suppliers", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshTestJButton)
                .addGap(93, 93, 93))
            .addComponent(jtabWork, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(refreshTestJButton)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jtabWork))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

       populateTableSupplier();
       populateComboSupplier(); 
       populateTableRequest();
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String str = (String)comboSupplierID.getSelectedItem();
        int supID = Integer.parseInt(str);
        String supName = (String)comboSupplierName.getSelectedItem();
        ArrayList<Supplier> tempSup = new ArrayList<Supplier>();

        for(Supplier sup:supplierDirectory.getSupplierList()){

            if(sup.getSupplierID()==supID||sup.getSupplierName().equals(supName)){
                tempSup.add(sup);
            }
        }

        DefaultTableModel model = (DefaultTableModel) tableSuppliers.getModel();

        model.setRowCount(0);
        for (Supplier supplier : tempSup){
            Object[] row = new Object[2];
            row[0] = supplier;
            row[1] = supplier.getSupplierName();

            model.addRow(row);
        }
        comboSupplierID.setSelectedIndex(0);
        comboSupplierName.setSelectedIndex(0);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        // TODO add your handling code here:
        AddNewSupplierPanel add = new AddNewSupplierPanel(userProcessContainer,supplierDirectory);
        userProcessContainer.add("AddSupplierJPanel",add);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.show(userProcessContainer, "AddSupplierJPanel");
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void btnDeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSupplierActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableSuppliers.getSelectedRow();
        if (selectedRow >= 0 ){
            int res = JOptionPane.showConfirmDialog(null, "Are you sure to delete this supplier?", "Yes or No", JOptionPane.YES_NO_OPTION);
            if(res == JOptionPane.YES_OPTION){
                Supplier s = (Supplier) tableSuppliers.getValueAt(selectedRow, 0);
                supplierDirectory.getSupplierList().remove(s);
                populateTableSupplier();
                populateComboSupplier();
            }

        }
        else
        JOptionPane.showMessageDialog(null, "Please select a supplier");
    }//GEN-LAST:event_btnDeleteSupplierActionPerformed

    /*
    *View Supplier details
    *
    */
    private void btnViewSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSupplierActionPerformed
        // TODO add your handling code here:
        //ViewSupplierDetailPanel viewSupplier = new ViewSupplierDetailPanel();
        int selectedRow = tableSuppliers.getSelectedRow();
        if (selectedRow >= 0 ){
            Supplier s = (Supplier) tableSuppliers.getValueAt(selectedRow, 0);
            ViewSupplierDetailPanel viewSupplierPanel = new ViewSupplierDetailPanel(userProcessContainer,s);
            userProcessContainer.add("ViewSupplierJPanel",viewSupplierPanel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.show(userProcessContainer, "ViewSupplierJPanel");
        }
        else
        JOptionPane.showMessageDialog(null, "Please select a supplier");

    }//GEN-LAST:event_btnViewSupplierActionPerformed

    private void btnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableRequest.getSelectedRow();
        if (selectedRow >= 0 ){
            WorkRequest req = (WorkRequest) tableRequest.getValueAt(selectedRow, 0);
            int res = JOptionPane.showConfirmDialog(null, "Are you sure to decline the request?", "Decline the request", JOptionPane.YES_NO_OPTION);
            if(res == JOptionPane.YES_OPTION){
                Enterprise enterprise = getSalesEnterprise();
                
                
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if (organization instanceof WarehouseOrganization && organization.getOrganizationID()!=3){
                        for(WorkRequest request:organization.getWorkQueue().getWorkRequestList()){
                            if(request.getRequestDate().equals(req.getRequestDate())){
                                request.setStatus("Request declined");
                                request.setEnterSender("Supplier Agency");
                                JOptionPane.showMessageDialog(null, "Request declined!");
                                break;
                            }
                        }
                    }
                }
            }
            
        }
        else
            JOptionPane.showMessageDialog(null, "Please select any rows");
    }//GEN-LAST:event_btnDeclineActionPerformed

    private void btnViewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableRequest.getSelectedRow();
        if (selectedRow >= 0 ){
            SignSupplierRequest req = (SignSupplierRequest) tableRequest.getValueAt(selectedRow, 0);
            ViewRequestPanel panel = new ViewRequestPanel(userProcessContainer,req);
            userProcessContainer.add("ViewRequestPanel",panel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.show(userProcessContainer,"ViewRequestPanel");
        }
        else
            JOptionPane.showMessageDialog(null, "Please select any rows");
    }//GEN-LAST:event_btnViewRequestActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableRequest.getSelectedRow();
        if (selectedRow >= 0 ){
            SignSupplierRequest req = (SignSupplierRequest) tableRequest.getValueAt(selectedRow, 0);
            ApproveRequestPanel panel = new ApproveRequestPanel(userProcessContainer,req,system,userAccount);
            userProcessContainer.add("ApproveRequestPanel",panel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.show(userProcessContainer,"ApproveRequestPanel");
        }
        else
            JOptionPane.showMessageDialog(null, "Please select any rows");
    }//GEN-LAST:event_btnApproveActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnDecline;
    private javax.swing.JButton btnDeleteSupplier;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewRequest;
    private javax.swing.JButton btnViewSupplier;
    private javax.swing.JComboBox<String> comboSupplierID;
    private javax.swing.JComboBox<String> comboSupplierName;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jtabWork;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JTable tableRequest;
    private javax.swing.JTable tableSuppliers;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

    protected void populateTableRequest() {
      
        DefaultTableModel model = (DefaultTableModel) tableRequest.getModel();

        model.setRowCount(0);
        ArrayList<WorkRequest> reList =organization.getWorkQueue().getWorkRequestList();
        for (WorkRequest request : reList){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getSender();
            row[2] = request.getMessage();
            row[3] = request.getStatus();

            model.addRow(row);
        }
    }

        
   private final Network getNetwork(){
       
        for(Network network: networkList){
            if(network.getName().equals("1")){
                System.out.println("看看network: "+network);
                return network;
            }
        }
        return null;
    }
    
    private final Enterprise getSalesEnterprise(){
        Network net = getNetwork();
        
        for(Enterprise enterprise:net.getEnterpriseDirectory().getEnterpriseList()){
            System.out.println("Let me see the enterprise Name: "+enterprise.getName());
            if(enterprise.getName().equals("XX"))
                return enterprise;
        } 
        
        return null;
    }
  
    
    void giveSupplier(){
        Enterprise enterprise = getSalesEnterprise();
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof WarehouseOrganization){
                    ((WarehouseOrganization) organization).setSupplierDierectory(supplierDirectory);
                }
            }     
    }
    
}
