/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LogisticsAssignCenter;

import Business.Dao.CourierOrder;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.LogisticsEnterprise;
import Business.Organization.CourierOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AssignWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author zlt1997
 */
public class UpdateOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateOrderJPanel
     */
    JPanel userProcessContainer;
    CourierOrder courierOrder;
    Enterprise enterprise;
    UserAccount userAccount;

    public UpdateOrderJPanel(JPanel userProcessContainer, CourierOrder courierOrder,Enterprise enterprise,UserAccount userAccount) {
                initComponents();
                this.userProcessContainer=userProcessContainer;
                this.courierOrder=courierOrder;
                this.enterprise=enterprise;
                this.userAccount=userAccount;
                combobox();
                OrderNum.setText(String.valueOf(courierOrder.getOrderNum()));
                TransportNum.setText(String.valueOf(this.courierOrder.getTransportNum()));
                
    }
    
    public void combobox()
    {
         for (Employee employee : enterprise.searchOrganization("Courier Organization").getEmployeeDirectory().getEmployeeList()) {
             //if (!employee.getRole().equals("Courier Role")) {
                        CourierSelect.addItem(employee.getEmployeeName());
                    //}
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CourierSelect = new javax.swing.JComboBox<>();
        OrderNum = new javax.swing.JLabel();
        TransportNum = new javax.swing.JLabel();
        Btnconfirm = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 237, 237));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 204));
        jLabel1.setText("Assign Work");

        jLabel2.setForeground(new java.awt.Color(255, 102, 204));
        jLabel2.setText("OrderNum:");

        jLabel3.setForeground(new java.awt.Color(255, 102, 204));
        jLabel3.setText("TransportNum:");

        jLabel4.setForeground(new java.awt.Color(255, 102, 204));
        jLabel4.setText("Courier:");

        CourierSelect.setForeground(new java.awt.Color(255, 102, 204));

        OrderNum.setForeground(new java.awt.Color(255, 102, 204));
        OrderNum.setText("jLabel5");

        TransportNum.setForeground(new java.awt.Color(255, 102, 204));
        TransportNum.setText("jLabel6");

        Btnconfirm.setForeground(new java.awt.Color(255, 102, 204));
        Btnconfirm.setText("Confirm");
        Btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnconfirmActionPerformed(evt);
            }
        });

        btnBack.setForeground(new java.awt.Color(255, 102, 204));
        btnBack.setText("<- Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(92, 92, 92)
                                .addComponent(CourierSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TransportNum))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(83, 83, 83)
                                    .addComponent(OrderNum)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(Btnconfirm)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBack)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(OrderNum))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TransportNum))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CourierSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(Btnconfirm)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnconfirmActionPerformed
        AssignWorkRequest request = new AssignWorkRequest();
        request.setCurOrder(courierOrder);
        request.setSender(userAccount);
        request.setStatus("Sent");
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof CourierOrganization){
                org = organization;
                break;
            }
        }
         if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
        }
        String username="";
        for (Employee employee : enterprise.searchOrganization("Courier Organization").getEmployeeDirectory().getEmployeeList()) {
            if (employee.getEmployeeName().equals(CourierSelect.getSelectedItem())) {
                username=employee.getEmployeeName();
            }
        }
        courierOrder.setCourierName(username);
        for (UserAccount ua : enterprise.searchOrganization("Courier Organization").getUserAccountDirectory().getUserAccountList()) {
              if (ua.getEmployee().getEmployeeName().equals(username)) {
                 request.setReceiver(ua);
                 request.setStatus("Received");
                 System.out.println(request.getStatus());
                 ua.getWorkQueue().getWorkRequestList().add(request);
                 userAccount.getWorkQueue().getWorkRequestList().add(request);
                 System.out.println(request.getStatus());
            }
        }
 

        // TODO add your handling code here:
    }//GEN-LAST:event_BtnconfirmActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        Component[] comps=this.userProcessContainer.getComponents();
        for(Component comp:comps)
        {
            if (comp instanceof AssignWorkAreaJPanel) {
                AssignWorkAreaJPanel manageP=(AssignWorkAreaJPanel) comp;
                manageP.populateTable();
            }
        }
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnconfirm;
    private javax.swing.JComboBox<String> CourierSelect;
    private javax.swing.JLabel OrderNum;
    private javax.swing.JLabel TransportNum;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
