/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.customer;

import Travel_Agency.Flight;
import Travel_Agency.Flights;
import Travel_Agency.Airplane;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author llm
 */
public class FlightDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FlightDetailsJPanel
     */
    public JPanel processPanel;
    public Flight flight;
    public FlightDetailsJPanel(JPanel processPanel, Flight flight) {
        initComponents();
        this.processPanel = processPanel;
        this.flight = flight;
        viewFlight(flight);
    }
    
    private void viewFlight(Flight flight){
        flightID.setText(flight.getFlightID());
        depart.setText(flight.getFromAirport());
        arrival.setText(flight.getToAirport());
        DateFormat df = DateFormat.getDateInstance(DateFormat.SHORT);
        date.setText(df.format(flight.getArriveDate()));
        time.setText(flight.getTime());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        flightNumLable = new javax.swing.JLabel();
        departureLable1 = new javax.swing.JLabel();
        departureLable = new javax.swing.JLabel();
        arriveLable = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        flightID = new javax.swing.JLabel();
        depart = new javax.swing.JLabel();
        arrival = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(102, 51, 255));

        backBtn.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        backBtn.setForeground(new java.awt.Color(102, 102, 255));
        backBtn.setText("< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        title.setForeground(new java.awt.Color(102, 51, 255));
        title.setText("Flight Details");

        flightNumLable.setForeground(new java.awt.Color(102, 51, 255));
        flightNumLable.setText("Flight Number");

        departureLable1.setForeground(new java.awt.Color(102, 51, 255));
        departureLable1.setText("Time ");

        departureLable.setForeground(new java.awt.Color(102, 51, 255));
        departureLable.setText("Departure Location");

        arriveLable.setForeground(new java.awt.Color(102, 51, 255));
        arriveLable.setText("Arrival  Location");

        dateLable.setForeground(new java.awt.Color(102, 51, 255));
        dateLable.setText("Date");

        flightID.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        flightID.setForeground(new java.awt.Color(102, 51, 255));
        flightID.setText("FlightIDLable");

        depart.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        depart.setForeground(new java.awt.Color(102, 51, 255));
        depart.setText("DepartLable");

        arrival.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        arrival.setForeground(new java.awt.Color(102, 51, 255));
        arrival.setText("ArrivalLable");

        date.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        date.setForeground(new java.awt.Color(102, 51, 255));
        date.setText("DateLable");

        time.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        time.setForeground(new java.awt.Color(102, 51, 255));
        time.setText("TimeLable");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(flightNumLable, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(flightID, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(departureLable, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(depart))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateLable, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(date))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)
                        .addGap(214, 214, 214)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arriveLable)
                            .addComponent(departureLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(time)
                            .addComponent(arrival))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightNumLable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightID))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departureLable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arriveLable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrival)
                    .addComponent(depart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departureLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date)
                    .addComponent(time))
                .addGap(152, 152, 152))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.processPanel.remove(this);
        CardLayout layout = (CardLayout)this.processPanel.getLayout();
        layout.previous(processPanel);
        
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrival;
    private javax.swing.JLabel arriveLable;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dateLable;
    private javax.swing.JLabel depart;
    private javax.swing.JLabel departureLable;
    private javax.swing.JLabel departureLable1;
    private javax.swing.JLabel flightID;
    private javax.swing.JLabel flightNumLable;
    private javax.swing.JLabel time;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
