/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.customer;

import Travel_Agency.Flight;
import Travel_Agency.Flights;
import Travel_Agency.Airplane;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author llm
 */
public class FlightsFoundJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Flightsfoundjpane
     */
    public JPanel processPanel;
    public Flights flights;
    public FlightsFoundJPanel(JPanel processPanel,Flights flights){
        initComponents();
        this.processPanel = processPanel;
        this.flights = flights;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)flightTable.getModel();
        dtm.setRowCount(0);
        DateFormat df = DateFormat.getDateInstance(DateFormat.SHORT);
        for(Flight flight: flights.getFlights()){
            Object row[] = new Object[5];
            row[0] = flight;
            row[1] = flight.getFromAirport();
            row[2] = flight.getToAirport();
            row[3] = df.format(flight.getArriveDate());
            row[4] = flight.getTime();
            dtm.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        flightTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        detaiBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        flightTable.setBackground(new java.awt.Color(153, 102, 255));
        flightTable.setForeground(new java.awt.Color(255, 255, 255));
        flightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "Departure location", "Arrival location", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(flightTable);

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        backBtn.setForeground(new java.awt.Color(102, 102, 255));
        backBtn.setText("< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        title.setForeground(new java.awt.Color(102, 51, 255));
        title.setText("Best Flight Found");

        detaiBtn.setForeground(new java.awt.Color(102, 51, 255));
        detaiBtn.setText("Details");
        detaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detaiBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(detaiBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(title)
                        .addGap(247, 247, 247)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(detaiBtn)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.processPanel.remove(this);
        CardLayout layout = (CardLayout)this.processPanel.getLayout();
        layout.previous(processPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void detaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detaiBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = flightTable.getSelectedRow();
        if (selectedRow >= 0 ){
            Flight flight = (Flight) flightTable.getValueAt(selectedRow, 0);
            FlightDetailsJPanel panel = new FlightDetailsJPanel(processPanel,flight);
            processPanel.add("FlightDetailsJPanel",panel);
            CardLayout layout = (CardLayout)processPanel.getLayout();
            layout.next(processPanel);
        }
        else
            JOptionPane.showMessageDialog(null, "Please select any rows");
    }//GEN-LAST:event_detaiBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton detaiBtn;
    private javax.swing.JTable flightTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
