/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.customer;

import Travel_Agency.Flight;
import Business.Tickets;
import Business.Ticket;
import Travel_Agency.Flights;
import java.awt.CardLayout;
import java.awt.Panel;
import java.text.DateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author llm
 */
public class ReserveSeats extends javax.swing.JPanel {

    /**
     * Creates new form CreateTicket
     */
    private Flight flight;
    private Tickets tickets;
    private JPanel processPanel;
    private Flights flightlist;
    private String SelectedFlightNo;
    private String selectedCustomerNo;
    
    
    public ReserveSeats(JPanel processPanel,Tickets tickets,Flights flightlist) {
        initComponents();
        this.tickets = tickets;
        this.processPanel = processPanel;
        this.flightlist=flightlist;
        this.flight=new Flight();
        populateTicket();
    }
    
    public void populateTicket(){
        DefaultTableModel dtm = (DefaultTableModel)ticketTable.getModel();
        dtm.setRowCount(0);
        for(Ticket ticket: tickets.getTickets()){
            Object row[] = new Object[5];
            row[0] = ticket.getCustomerID();
            row[1] = ticket.getFlightID();
            row[2] = ticket.getSeatName();
            dtm.addRow(row);
            
        }
       }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        seatTable = new javax.swing.JTable();
        reserveBtn = new javax.swing.JButton();
        availBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ticketTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        title.setForeground(new java.awt.Color(102, 51, 255));
        title.setText("Reserve Seats");

        seatTable.setBackground(new java.awt.Color(153, 102, 255));
        seatTable.setForeground(new java.awt.Color(255, 255, 255));
        seatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seat Name", "Row", "Column", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(seatTable);

        reserveBtn.setForeground(new java.awt.Color(102, 51, 255));
        reserveBtn.setText("Reserve");
        reserveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveBtnActionPerformed(evt);
            }
        });

        availBtn.setForeground(new java.awt.Color(102, 51, 255));
        availBtn.setText("Seat Available");
        availBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availBtnActionPerformed(evt);
            }
        });

        ticketTable.setBackground(new java.awt.Color(153, 102, 255));
        ticketTable.setForeground(new java.awt.Color(255, 255, 255));
        ticketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customet ID", "Flight ID", "Seat"
            }
        ));
        jScrollPane2.setViewportView(ticketTable);

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(153, 153, 255));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(343, 343, 343)
                                .addComponent(reserveBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(296, 296, 296)
                                .addComponent(title))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(316, 316, 316)
                                .addComponent(availBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(34, 34, 34)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(availBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reserveBtn)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void availBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availBtnActionPerformed
        // TODO add your handling code here:
        int Selectedticket = ticketTable.getSelectedRow();
        if (Selectedticket< 0)
        {
        JOptionPane.showMessageDialog(null,"Please select row from the Table first to view","Warning",JOptionPane.WARNING_MESSAGE);
        return;
                }
        else{
         
            if (ticketTable.getValueAt(Selectedticket, 2)!=null) {
                JOptionPane.showMessageDialog(this, "Already have seat");
                return;
            }
            selectedCustomerNo=(String)ticketTable.getValueAt(Selectedticket,0);
            SelectedFlightNo=(String)ticketTable.getValueAt(Selectedticket,1);
            flight=flightlist.searchFlightbyNo(SelectedFlightNo);
        }
        populateTable(flight);
    }//GEN-LAST:event_availBtnActionPerformed
    
    public String getType(int column){
        StringBuilder a = new StringBuilder();
        switch(column){
            case 0:
                a.append("Left Window");
                break;
            case 1:
                a.append("Left Middle");
                break;
            case 2:
                a.append("Left Aisle"); 
                break;
            case 3:
                a.append("Right Aisle");
                break;
            case 4:
                a.append("Right Middle");  
                break;
            case 5:
                a.append("Right Window"); 
                break;
                 
        }
        return a.toString();
        
    }
    
    public void populateTable(Flight flight){
        DefaultTableModel dtm = (DefaultTableModel)seatTable.getModel();
        dtm.setRowCount(0);
        DateFormat df = DateFormat.getDateInstance(DateFormat.SHORT);
        for (int i = 0; i < 25; i++) {
            for (int j = 0; j < 6; j++) {
                Object row[] = new Object[4];
                row[0] = flight.nameoftheseat(i+1,j+1);
                row[1] = i+1;
                row[2] = j+1;
                row[3] = getType(j);
                System.out.println(getType(1));
                if(flight.isavaliable(i,j)){
                   dtm.addRow(row);
               
                }
               
           }
       }
        
    }
    
    private void reserveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = seatTable.getSelectedRow();
        if (selectedRow >= 0 ){
            int row = (Integer)seatTable.getValueAt(selectedRow,1);
            int column = (Integer)seatTable.getValueAt(selectedRow,2);
            flight.setAvail(row-1, column-1);  
            populateTable(flight);            
            Ticket ticket = tickets.SearchTicket(selectedCustomerNo,SelectedFlightNo);
            ticket.setSeatName((String)seatTable.getValueAt(selectedRow,0));
            JOptionPane.showMessageDialog(this, "Book Successfully");
            populateTicket();
        }
        else
            JOptionPane.showMessageDialog(null, "Please select any rows");
        
    }//GEN-LAST:event_reserveBtnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        processPanel.remove(this);
        CardLayout layout = (CardLayout)(processPanel).getLayout();
        layout.first(processPanel);
    }//GEN-LAST:event_btnBackActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton availBtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton reserveBtn;
    private javax.swing.JTable seatTable;
    private javax.swing.JTable ticketTable;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
